tasks:
  - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with omething that should run on every start, or just
      remove me entirely."
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - hars.CppSnippets@0.0.14:d9VwbSfM8Lu6jSqLKsmohg==